/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'diogo' at '4/24/15 12:50 PM' with Gradle 2.3
 *
 * @author diogo, @date 4/24/15 12:50 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
