/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'diogo' at '4/24/15 12:50 PM' with Gradle 2.3
 *
 * @author diogo, @date 4/24/15 12:50 PM
 */

/*
import groovyx.net.http.RESTClient
import static groovyx.net.http.ContentType.JSON


restClient = new RESTClient( 'http://localhost:8080/CustomerDB/webresources/', JSON)
def resp = restClient.get(path: 'entities.customer')
assert resp.status == 200
println resp.data
def respHeaders = resp.getAllHeaders()
respHeaders.each { header ->
 println header
}
*/

import spock.lang.Specification
import groovyx.net.http.RESTClient
import static groovyx.net.http.ContentType.JSON

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        //Library lib = new Library()
        Main.initServer()
        when:
        //def result = lib.someLibraryMethod()
        def client = new RESTClient("http://localhost:4567/", JSON)
        def resp = client.get(path : "swagger")
        println resp
        then:
        resp.status == 200
    }
}
